spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/db_social?useUnicode=true&serverTimezone=Europe/Moscow&useSSL=true&verifyServerCertificate=false
    username: springuser
    password: ThePassword
  liquibase:
    user: springuser
    password: ThePassword
    change-log: classpath:/liquibase/changelog.xml
    url: "jdbc:mysql://localhost:3306/db_social?useUnicode=true&serverTimezone=Europe/Moscow&useSSL=true&verifyServerCertificate=false"
    database-change-log-table: network_databaseChangeLog
    database-change-log-lock-table: network_databaseChangeLogLock
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp